### ISSUE TITLE
ModuleNotFoundError: No module named 'rich'

### ISSUE THREAD

**Issue by LeoMusk** [shadowcz007/comfyui-liveportrait#2]
bro，一致报错。用pip install和python_embeded里面的python 都装了rich，但还是报错o(╥﹏╥)o。

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-layerdiffusion module for custom nodes: name 'MidBlock2D' is not defined
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-liveportrait\__init__.py", line 1, in <module>
    from .nodes.live_portrait import LivePortraitNode
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-liveportrait\nodes\live_portrait.py", line 27, in <module>
    from .LivePortrait.src.live_portrait_pipeline import LivePortraitPipeline
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-liveportrait\nodes\LivePortrait\src\live_portrait_pipeline.py", line 15, in <module>
    from rich.progress import track
ModuleNotFoundError: No module named 'rich'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-liveportrait module for custom nodes: No module named 'rich'

**Comment by LeoMusk** [comment]
参考原项目的依赖，安装后，ok了
