### ISSUE TITLE
使用全家福json运行中报错

### ISSUE THREAD

**Issue by g711ab** [shadowcz007/comfyui-liveportrait#34]
#crop_info dict_keys(['M_o2c', 'M_c2o', 'img_crop', 'pt_crop', 'img_crop_256x256', 'pt_crop_256x256', 'lmk_crop'])
!!! Exception during processing!!! 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/data/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/ComfyUI/execution.py", line 65, in map_node_over_list
    results.append(getattr(obj, func)(**input_data_all))
  File "/data/ComfyUI/custom_nodes/comfyui-liveportrait/nodes/live_portrait.py", line 407, in run
    live_portrait_pipeline.executeForAll(args)
  File "/data/ComfyUI/custom_nodes/comfyui-liveportrait/nodes/LivePortrait/src/live_portrait_pipeline.py", line 353, in executeForAll
    lip_delta_before_animation = self.live_portrait_wrapper.retarget_lip(x_s, combined_lip_ratio_tensor_before_animation)
  File "/data/ComfyUI/custom_nodes/comfyui-liveportrait/nodes/LivePortrait/src/live_portrait_wrapper.py", line 224, in retarget_lip
    delta = self.stitching_retargeting_module['lip'](feat_lip)
TypeError: 'NoneType' object is not subscriptable

**Comment by g711ab** [comment]
stitching_retargeting_module.pth 放错了路径导致的

**Comment by tutnyal** [comment]
which directory should it be in?

**Comment by g711ab** [comment]
> stitching_retargeting_module.pth

./models/liveportrait/retargeting_models/stitching_retargeting_module.pth

**Comment by DBX8466** [comment]
> > stitching_retargeting_module.pth
> 
> ./models/liveportrait/retargeting_models/stitching_retargeting_module.pth

Thank you very much, I was troubled by this for 3 days until I read your reply

**Comment by dongguo4812** [comment]
Thank you very much, You saved me
