### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by robji15** [shadowcz007/comfyui-liveportrait#41]
writing 1008
Dump to K:\ComfyUI-aki-v1\temp\live_portrait_00000.mp4

#scenes_video [0] ['K:\\ComfyUI-aki-v1\\temp\\live_portrait_00000.mp4']
total_frame_count 1008
Using fallback file for extremely long metadata: 7919798/32567
!!! Exception during processing !!! [Errno 22] Invalid argument
Traceback (most recent call last):
  File "K:\ComfyUI-aki-v1\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI-aki-v1\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI-aki-v1\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "K:\ComfyUI-aki-v1\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI-aki-v1\custom_nodes\comfyui-mixlab-nodes\nodes\Video.py", line 805, in run
    self.save_with_tempfile(args, metadata_args[1], file_path, frames, env)
  File "K:\ComfyUI-aki-v1\custom_nodes\comfyui-mixlab-nodes\nodes\Video.py", line 689, in save_with_tempfile
    proc.stdin.write(frame.tobytes())
OSError: [Errno 22] Invalid argument

**Comment by robji15** [comment]
writing 24
Dump to K:\ComfyUI-aki-v1\temp\live_portrait_00000.mp4

#scenes_video [0] ['K:\\ComfyUI-aki-v1\\temp\\live_portrait_00000.mp4']
total_frame_count 24
Using fallback file for extremely long metadata: 1823294/32568
!!! Exception during processing !!! [Errno 32] Broken pipe
Traceback (most recent call last):
  File "K:\ComfyUI-aki-v1\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI-aki-v1\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI-aki-v1\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "K:\ComfyUI-aki-v1\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI-aki-v1\custom_nodes\comfyui-mixlab-nodes\nodes\Video.py", line 805, in run
    self.save_with_tempfile(args, metadata_args[1], file_path, frames, env)
  File "K:\ComfyUI-aki-v1\custom_nodes\comfyui-mixlab-nodes\nodes\Video.py", line 689, in save_with_tempfile
    proc.stdin.write(frame.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

Prompt executed in 37.66 seconds
Task exception was never retrieved
future: <Task finished name='Task-44' coro=<RequestHandler.start() done, defined at K:\ComfyUI-aki-v1\.ext\Lib\site-packages\aiohttp\web_protocol.py:493> exception=AssertionError()>
Traceback (most recent call last):
  File "K:\ComfyUI-aki-v1\.ext\Lib\site-packages\aiohttp\web_protocol.py", line 536, in start
    request = self._request_factory(message, payload, self, writer, handler)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI-aki-v1\.ext\Lib\site-packages\aiohttp\web_app.py", line 479, in _make_request
    return _cls(
           ^^^^^
  File "K:\ComfyUI-aki-v1\.ext\Lib\site-packages\aiohttp\web_request.py", line 841, in __init__
    super().__init__(*args, **kwargs)
  File "K:\ComfyUI-aki-v1\.ext\Lib\site-packages\aiohttp\web_request.py", line 196, in __init__
    assert transport is not None
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
